"""The held-out evaluation set. Authored by hand, never generated.

This is the honest number in the evaluation. The generator in
generate_dataset.py has never seen these strings, they use a deliberately
different register — terse, misspelled, code-switched mid-sentence, angry — and
a block of them is genuinely unclassifiable on purpose.

A model that only memorised template vocabulary fails visibly here. That gap
between synthetic-holdout accuracy and gold accuracy is a measurement, not a
flaw to hide.

`category = None` means "no single correct label": the pipeline should return
low confidence and route to human triage rather than pick something.
"""

from app.domain.taxonomy import Category

# (subject, text, category | None)
GOLD: list[tuple[str, str, str | None]] = [
    # -------------------------------------------------------- CARTE_BANCAIRE
    ("carte", "el machine bel3atli el karta w l agence t9oli stanna 15 jour",
     Category.CARTE_BANCAIRE),
    ("Carte bloquee", "ma carte marche plus depuis mardi personne sait pourquoi",
     Category.CARTE_BANCAIRE),
    ("reclamation", "البطاقة متاعي مسكرة و ما نعرفش علاش، الحساب فيه فلوس",
     Category.CARTE_BANCAIRE),
    ("CARTE", "JE PAYE 40DT PAR AN POUR UNE CARTE QUI MARCHE JAMAIS",
     Category.CARTE_BANCAIRE),
    ("renouvellement", "carte expiree en mars, la nouvelle jamais arrivee a l agence",
     Category.CARTE_BANCAIRE),
    ("opposition", "j ai fait opposition lundi et y a eu 2 achats mardi",
     Category.CARTE_BANCAIRE),
    ("card", "my card was swallowed by your atm and nobody helps",
     Category.CARTE_BANCAIRE),
    ("karta", "karti ma5dmch fel magasin ama fel distributeur tekhdem, chnowa hedha",
     Category.CARTE_BANCAIRE),
    ("plafond", "vous avez baisse mon plafond a 200dt sans me prevenir",
     Category.CARTE_BANCAIRE),
    ("Carte perdue", "carte perdue signalee samedi toujours pas remplacee",
     Category.CARTE_BANCAIRE),
    ("bloquee", "3 fois que je demande le deblocage de ma carte rien ne bouge",
     Category.CARTE_BANCAIRE),
    ("البطاقة", "طلبت بطاقة جديدة من شهرين و حتى اليوم ما وصلتنيش",
     Category.CARTE_BANCAIRE),

    # --------------------------------------------------------------- DAB_GAB
    ("retrait", "el distributeur 5a l flous w ma5rejch waraq, 200dt",
     Category.DAB_GAB),
    ("PROBLEME", "300 DT DEBITES ET RIEN N EST SORTI DE LA MACHINE",
     Category.DAB_GAB),
    ("distributeur", "الموزع خذا 500 دينار و ما خرجش شيء و انا مستني من اسبوع",
     Category.DAB_GAB),
    ("retrait rate", "j ai demande 400 il m a donne 300 et debite 400",
     Category.DAB_GAB),
    ("gab", "le gab de la marsa hors service depuis 3 semaines c est le seul du coin",
     Category.DAB_GAB),
    ("atm", "atm took my money no cash dispensed reference op8823141",
     Category.DAB_GAB),
    ("machine", "operation annulee par la machine mais compte debite quand meme",
     Category.DAB_GAB),
    ("retrait double", "un seul retrait fait deux lignes sur mon releve",
     Category.DAB_GAB),
    ("guichet auto", "ca fait 1 mois que j attends le remboursement du retrait rate",
     Category.DAB_GAB),
    ("moziaa", "el moziia3 mte3 sousse dima 5arban, kol marra nemchi w nerja3",
     Category.DAB_GAB),
    ("billets", "billets non delivres et l agence me parle de compensation je comprends rien",
     Category.DAB_GAB),

    # -------------------------------------------------- PAIEMENT_TPE_ECOMMERCE
    ("paiement", "khalast marra wa7da 3and el pharmacien w el releve ybayen zouz",
     Category.PAIEMENT_TPE_ECOMMERCE),
    ("Double debit", "180dt preleves 2 fois pour un seul achat au monoprix",
     Category.PAIEMENT_TPE_ECOMMERCE),
    ("achat en ligne", "j ai paye ma commande 2 fois le site dit une seule",
     Category.PAIEMENT_TPE_ECOMMERCE),
    ("code sms", "jamais recu le code pour valider mes achats internet",
     Category.PAIEMENT_TPE_ECOMMERCE),
    ("refus", "ma carte est refusee partout alors que j ai 3000dt sur le compte",
     Category.PAIEMENT_TPE_ECOMMERCE),
    ("الدفع", "خلصت في المغازة و المبلغ تنقص مرتين، عندي التذكرة",
     Category.PAIEMENT_TPE_ECOMMERCE),
    ("tpe", "le tpe a affiche echec et pourtant j ai ete debite",
     Category.PAIEMENT_TPE_ECOMMERCE),
    ("online payment", "charged twice for one online order please refund",
     Category.PAIEMENT_TPE_ECOMMERCE),
    ("3ds", "el code 3d secure ma yjinich w ma nejjemch nechri online",
     Category.PAIEMENT_TPE_ECOMMERCE),
    ("commercant", "paiement passe chez le commercant mais lui dit qu il n a rien recu",
     Category.PAIEMENT_TPE_ECOMMERCE),

    # -------------------------------------------------- VIREMENT_PRELEVEMENT
    ("virement", "virement fait le 3 toujours pas arrive on est le 19",
     Category.VIREMENT_PRELEVEMENT),
    ("SALAIRE", "MON SALAIRE N EST PAS ARRIVE ET JE DOIS PAYER LE LOYER",
     Category.VIREMENT_PRELEVEMENT),
    ("transfert", "التحويل متاعي من 10 ايام و المستفيد ما وصلوش شيء",
     Category.VIREMENT_PRELEVEMENT),
    ("prelevement", "vous prelevez encore une assurance que j ai resiliee en janvier",
     Category.VIREMENT_PRELEVEMENT),
    ("rib", "virement parti sur mon ancien rib alors que j ai donne le nouveau",
     Category.VIREMENT_PRELEVEMENT),
    ("virement perm", "mon virement permanent n a jamais ete mis en place",
     Category.VIREMENT_PRELEVEMENT),
    ("paie", "el paie mte3i ma wsaletch w el patron 3malha, chnowa el mochkla",
     Category.VIREMENT_PRELEVEMENT),
    ("transfer", "sent 2000dt internally 8 days ago beneficiary got nothing",
     Category.VIREMENT_PRELEVEMENT),
    ("virement bloque", "virement en attente depuis une semaine sans explication",
     Category.VIREMENT_PRELEVEMENT),
    ("اقتطاع", "يقتطعوا من الحساب متاعي كل شهر و ما عندي حتى عقد معاهم",
     Category.VIREMENT_PRELEVEMENT),

    # --------------------------------------------------------- CHEQUE_EFFET
    ("chequier", "chequier commande y a 5 semaines toujours rien a l agence",
     Category.CHEQUE_EFFET),
    ("cheque rejete", "mon cheque est revenu impaye alors que j avais de quoi",
     Category.CHEQUE_EFFET),
    ("الشيك", "الشيك متاعي رجع و الحساب كان فيه فلوس، ضرني مع المزود",
     Category.CHEQUE_EFFET),
    ("remise", "cheque depose y a 12 jours pas encore credite",
     Category.CHEQUE_EFFET),
    ("opposition", "j ai fait opposition sur un cheque vole et il a ete paye quand meme",
     Category.CHEQUE_EFFET),
    ("chek", "talabt chekat men chhar w nos w ma3tawnich, w khalast el frais",
     Category.CHEQUE_EFFET),
    ("certification", "attente de 3 semaines pour certifier un cheque j ai perdu la vente",
     Category.CHEQUE_EFFET),
    ("cheque", "rejet pour provision insuffisante alors que le virement etait arrive la veille",
     Category.CHEQUE_EFFET),
    ("cheque book", "ordered a chequebook a month ago never received it",
     Category.CHEQUE_EFFET),

    # ------------------------------------------------------- COMPTE_GESTION
    ("cloture", "j ai demande la cloture en mars vous prelevez toujours des frais",
     Category.COMPTE_GESTION),
    ("releve", "plus aucun releve depuis 4 mois j en ai besoin pour ma compta",
     Category.COMPTE_GESTION),
    ("compte bloque", "compte bloque du jour au lendemain sans un sms",
     Category.COMPTE_GESTION),
    ("الحساب", "سكرو الحساب متاعي بلا ما يعلموني و ما نعرفش السبب",
     Category.COMPTE_GESTION),
    ("solde", "le solde de mon releve ne correspond pas aux operations ecart de 120dt",
     Category.COMPTE_GESTION),
    ("procuration", "demande de procuration pour ma femme deposee y a 6 semaines rien",
     Category.COMPTE_GESTION),
    ("compte joint", "vous avez transforme notre compte joint sans nous demander",
     Category.COMPTE_GESTION),
    ("nsakker", "talabt nsakker el compte w mazel ma7loul w el frais mazelou",
     Category.COMPTE_GESTION),
    ("statement", "no account statements for four months now",
     Category.COMPTE_GESTION),

    # -------------------------------------------------- CREDIT_FINANCEMENT
    ("credit", "l echeance est passee 2 fois ce mois 340dt en trop",
     Category.CREDIT_FINANCEMENT),
    ("mainlevee", "credit solde en janvier mainlevee toujours pas faite ca bloque ma vente",
     Category.CREDIT_FINANCEMENT),
    ("dossier", "ملف القرض متاعي من 3 اشهر و حتى واحد ما يجاوبني",
     Category.CREDIT_FINANCEMENT),
    ("taux", "le taux du contrat n est pas celui qu on m avait annonce",
     Category.CREDIT_FINANCEMENT),
    ("PENALITES", "VOUS ME FACTUREZ DES PENALITES ALORS QUE C EST VOTRE ERREUR",
     Category.CREDIT_FINANCEMENT),
    ("echeancier", "jamais recu le tableau d amortissement malgre 4 demandes",
     Category.CREDIT_FINANCEMENT),
    ("9ist", "el 9ist tna99es zouz marrat hedha chhar, rajj3ouli flousi",
     Category.CREDIT_FINANCEMENT),
    ("credit auto", "dossier depose en fevrier aucune reponse ni oui ni non",
     Category.CREDIT_FINANCEMENT),
    ("loan", "my loan instalment was taken twice this month",
     Category.CREDIT_FINANCEMENT),

    # --------------------------------------------------- FRAIS_COMMISSIONS
    ("agios", "des agios de 78dt alors que je n ai jamais ete a decouvert",
     Category.FRAIS_COMMISSIONS),
    ("frais", "vous prelevez 25dt par trimestre c est ecrit ou ca",
     Category.FRAIS_COMMISSIONS),
    ("مصاريف", "تنقصو مني مصاريف كل ثلاثية و ما فهمت علاش",
     Category.FRAIS_COMMISSIONS),
    ("commission", "commission de 45dt sur un virement de 200dt vous plaisantez",
     Category.FRAIS_COMMISSIONS),
    ("carte resiliee", "je paye encore la cotisation d une carte rendue y a 8 mois",
     Category.FRAIS_COMMISSIONS),
    ("frais dossier", "300dt de frais de dossier pour un credit que vous avez refuse",
     Category.FRAIS_COMMISSIONS),
    ("frais opposition", "vous me facturez l opposition alors que je suis victime de fraude",
     Category.FRAIS_COMMISSIONS),
    ("frais", "tna99sou meni 60 dinar frais w 3omri ma kont fel negatif",
     Category.FRAIS_COMMISSIONS),
    ("charges", "quarterly account fees never mentioned when i opened the account",
     Category.FRAIS_COMMISSIONS),

    # ------------------------------------------------------ BANQUE_DIGITALE
    ("appli", "l application se ferme des que je tape mon code",
     Category.BANQUE_DIGITALE),
    ("code bloque", "mon code d acces est bloque et le lien de deblocage n arrive jamais",
     Category.BANQUE_DIGITALE),
    ("التطبيق", "التطبيق ما يخدمش من اسبوع، نزلتو و رجعت نزلتو و نفس الشيء",
     Category.BANQUE_DIGITALE),
    ("otp", "je recois plus les codes sms donc je peux rien valider",
     Category.BANQUE_DIGITALE),
    ("app", "app crashes every time i open it useless",
     Category.BANQUE_DIGITALE),
    ("virement appli", "impossible de faire un virement depuis l appli erreur technique",
     Category.BANQUE_DIGITALE),
    ("solde appli", "le solde affiche dans l appli est faux par rapport au distributeur",
     Category.BANQUE_DIGITALE),
    ("application", "el application tetsakker wa7edha ki nhot el code",
     Category.BANQUE_DIGITALE),
    ("MAJ", "depuis la mise a jour plus rien ne fonctionne bravo",
     Category.BANQUE_DIGITALE),
    ("espace client", "impossible de me connecter a mon espace en ligne depuis 2 semaines",
     Category.BANQUE_DIGITALE),

    # ------------------------------------------ OPERATIONS_INTERNATIONALES
    ("allocation", "allocation touristique refusee sans motif et je pars dans 6 jours",
     Category.OPERATIONS_INTERNATIONALES),
    ("transfert", "virement recu de france y a 15 jours toujours pas credite",
     Category.OPERATIONS_INTERNATIONALES),
    ("change", "le taux applique n est pas celui affiche en agence ce jour la",
     Category.OPERATIONS_INTERNATIONALES),
    ("المنحة", "طلبت المنحة السياحية و رفضوها بلا سبب و السفرة قريبة",
     Category.OPERATIONS_INTERNATIONALES),
    ("carte devise", "ma carte devise n a jamais ete alimentee malgre le dossier complet",
     Category.OPERATIONS_INTERNATIONALES),
    ("swift", "sender has the swift confirmation you still say nothing received",
     Category.OPERATIONS_INTERNATIONALES),
    ("devises", "frais preleves sur un virement recu alors que c etait frais emetteur",
     Category.OPERATIONS_INTERNATIONALES),
    ("rapatriement", "impossible de rapatrier les fonds de mon compte en devises",
     Category.OPERATIONS_INTERNATIONALES),

    # ------------------------------- FRAUDE_OPERATION_NON_AUTORISEE
    ("URGENT", "3 operations que je n ai jamais faites 2400dt disparus de mon compte",
     Category.FRAUDE_OPERATION_NON_AUTORISEE),
    ("fraude", "retraits a tunis alors que j etais en italie avec ma carte sur moi",
     Category.FRAUDE_OPERATION_NON_AUTORISEE),
    ("عمليات", "فما عمليات في الحساب متاعي ما عملتهاش، 3000 دينار طاروا",
     Category.FRAUDE_OPERATION_NON_AUTORISEE),
    ("sms arnaque", "j ai repondu a un sms de votre banque et depuis on m a vide le compte",
     Category.FRAUDE_OPERATION_NON_AUTORISEE),
    ("achats inconnus", "des achats internet que je n ai jamais passes pour 890dt",
     Category.FRAUDE_OPERATION_NON_AUTORISEE),
    ("piratage", "quelqu un s est connecte a mon espace et a ajoute un beneficiaire",
     Category.FRAUDE_OPERATION_NON_AUTORISEE),
    ("flous", "5adhou flous men 7sabi bla ma na3ref, mouch ana eli 3malt hedhi",
     Category.FRAUDE_OPERATION_NON_AUTORISEE),
    ("unauthorized", "several transactions i never made totalling 1500dt",
     Category.FRAUDE_OPERATION_NON_AUTORISEE),
    ("vol", "ma carte etait dans mon portefeuille et pourtant elle a servi a sfax",
     Category.FRAUDE_OPERATION_NON_AUTORISEE),

    # -------------------------------------------- AGENCE_QUALITE_SERVICE
    ("attente", "1h30 d attente avec 2 guichets sur 5 ouverts c est chaque fois pareil",
     Category.AGENCE_QUALITE_SERVICE),
    ("chargee clientele", "ma chargee de clientele ne repond ni au tel ni aux mails",
     Category.AGENCE_QUALITE_SERVICE),
    ("الوكالة", "الانتظار في الوكالة يفوت الساعة و الموظفين قاعدين يهدرو",
     Category.AGENCE_QUALITE_SERVICE),
    ("accueil", "un agent m a parle mal devant tout le monde j attends des excuses",
     Category.AGENCE_QUALITE_SERVICE),
    ("horaires", "l agence ferme a 11h alors que l affiche dit 13h",
     Category.AGENCE_QUALITE_SERVICE),
    ("agence", "el agence mte3 lac 2 dima zahma w famech kan guichet wahed",
     Category.AGENCE_QUALITE_SERVICE),
    ("personnes agees", "ma mere de 78 ans a attendu debout 1h aucune priorite",
     Category.AGENCE_QUALITE_SERVICE),
    ("branch", "nobody at the branch could answer a simple question about my account",
     Category.AGENCE_QUALITE_SERVICE),

    # ------------------------------------------------------- unclassifiable
    # Genuinely ambiguous or content-free. The pipeline should report low
    # confidence and route to a human rather than invent a label.
    ("probleme", "bonjour j ai un probleme merci de me rappeler", None),
    ("reclamation", "ca fait 3 fois que j appelle personne ne fait rien", None),
    ("?", "chnowa hedha??", None),
    ("URGENT", "RAPPELEZ MOI IMMEDIATEMENT", None),
    ("aide", "السلام عليكم نحب نستفسر على حاجة", None),
    ("compte", "je ne comprends rien a ce qui se passe sur mon compte", None),
    ("bonjour", "bonjour", None),
    ("service", "votre service est une catastrophe", None),
    ("info", "3andi soual", None),
    ("hello", "i need help with my account please", None),
    ("reclamation formelle", "je souhaite deposer une reclamation formelle", None),
    ("mochkla", "3andi mochkla, chkoun najjem y3awenni", None),
    ("suivi", "ou en est mon dossier", None),
    ("رد", "مازلت نستنى الرد متاعكم", None),
    ("merci", "merci de traiter ma demande rapidement", None),
    ("banque", "je suis client chez vous depuis 15 ans et voila comment on me traite", None),
]
