"""The held-out evaluation set. Authored by hand, never generated.

This is the honest number in the evaluation. The generator in
generate_dataset.py has never seen these strings, they use a deliberately
different register — terse, misspelled, code-switched mid-sentence, angry — and
a block of them is genuinely unclassifiable on purpose.

A model that only memorised template vocabulary fails visibly here. That gap
between synthetic-holdout accuracy and gold accuracy is a measurement, not a
flaw to hide.

`category = None` means "no single correct label": the pipeline should return
low confidence and route to human triage rather than pick something.
"""

from app.domain.taxonomy import Category

# (subject, text, category | None)
GOLD: list[tuple[str, str, str | None]] = [
    # ------------------------------------------------------------ FACTURATION
    ("facture", "chnowa hedha 340 dinar?? ana ma3milt walou", Category.FACTURATION),
    ("Trop cher", "vous m avez pris 89 dt de plus ce mois pourquoi", Category.FACTURATION),
    ("reclamation", "الفاتورة فيها مبلغ ما نعرفوش شنو هو", Category.FACTURATION),
    ("Facture", "double paiement janvier + fevrier, remboursez", Category.FACTURATION),
    ("montant", "j ai un forfait a 25dt on me facture 61dt depuis 3 mois", Category.FACTURATION),
    ("PROBLEME FACTURE", "C EST DU VOL PUR ET SIMPLE 200 DINARS POUR RIEN", Category.FACTURATION),
    ("frais", "des frais de dossier jamais annonces sur ma derniere facture", Category.FACTURATION),
    ("facture erronee", "khalaset 120 dt w el consommation mte3i ma tetjawezch 40", Category.FACTURATION),
    ("Reclamation facture", "prelevement automatique effectue deux fois le meme jour", Category.FACTURATION),
    ("bill", "why am i charged twice for the same month", Category.FACTURATION),
    ("Facture juin", "la tva a ete appliquee deux fois sur ma facture de juin", Category.FACTURATION),
    ("فاتورة", "خصمولي المبلغ مرتين من البنكة", Category.FACTURATION),
    ("cher", "9adech hedha? 187 dt w ana ma sta3maltech", Category.FACTURATION),
    ("Contestation", "je conteste les 45 dinars de hors forfait, ma data etait coupee", Category.FACTURATION),
    ("facture", "montant different de celui annonce par le vendeur en boutique", Category.FACTURATION),

    # ------------------------------------------------- PAIEMENT_RECHARGE
    ("recharge", "3abbit 20 dinar w ma wsalnich walou", Category.PAIEMENT_RECHARGE),
    ("paiement", "carte debitee, facture toujours impayee dans mon espace", Category.PAIEMENT_RECHARGE),
    ("تعبئة", "عبيت الرصيد و ما زادش شي", Category.PAIEMENT_RECHARGE),
    ("recharge ratee", "3 tentatives de recharge, 3 echecs, argent parti", Category.PAIEMENT_RECHARGE),
    ("d17", "paiement d17 valide cote banque mais rien chez vous", Category.PAIEMENT_RECHARGE),
    ("solde", "credit disparu apres rechargement de 30dt hier soir", Category.PAIEMENT_RECHARGE),
    ("top up", "topped up 50 dinars, balance still zero after 2 hours", Category.PAIEMENT_RECHARGE),
    ("recharge", "el flous mchew mel carte w el solde 0", Category.PAIEMENT_RECHARGE),
    ("paiement refuse", "impossible de payer ma facture, erreur systeme a chaque fois", Category.PAIEMENT_RECHARGE),
    ("خلاص", "خلصت الفاتورة و مازالت تظهر غير مخلصة", Category.PAIEMENT_RECHARGE),
    ("rechargement", "j ai recharge sur le mauvais numero par erreur du systeme", Category.PAIEMENT_RECHARGE),
    ("credit", "mon credit a ete debite sans aucune consommation de ma part", Category.PAIEMENT_RECHARGE),
    ("recharge en ligne", "transaction TRX9982211 debitee mais non creditee", Category.PAIEMENT_RECHARGE),
    ("paiement", "e-dinar accepte puis annule, montant non restitue", Category.PAIEMENT_RECHARGE),
    ("recharge", "chariti recharge w ma khdemetch, 3lech?", Category.PAIEMENT_RECHARGE),

    # ------------------------------------------------------- RESEAU_MOBILE
    ("pas de reseau", "3 jours sans reseau a mourouj, rien ne marche", Category.RESEAU_MOBILE),
    ("شبكة", "ما فماش شبكة في الحومة الكل", Category.RESEAU_MOBILE),
    ("4g", "4g inutilisable des 20h, on dirait de la 2g", Category.RESEAU_MOBILE),
    ("appels", "mes appels coupent apres 20 secondes systematiquement", Category.RESEAU_MOBILE),
    ("reseau", "famech reseau fi sfax men lbera7", Category.RESEAU_MOBILE),
    ("couverture", "aucune barre chez moi alors que la carte annonce 4g+", Category.RESEAU_MOBILE),
    ("network", "no signal at all in my area for two days now", Category.RESEAU_MOBILE),
    ("SIGNAL", "AUCUN SIGNAL DEPUIS UNE SEMAINE C EST HONTEUX", Category.RESEAU_MOBILE),
    ("sms", "je ne recois plus aucun sms depuis lundi, les appels passent", Category.RESEAU_MOBILE),
    ("data", "internet mobile mort a hammamet tout le week end", Category.RESEAU_MOBILE),
    ("شبكة ضعيفة", "الاشارة ضعيفة برشة في الدار", Category.RESEAU_MOBILE),
    ("reseau", "obliged de sortir dans la rue pour telephoner", Category.RESEAU_MOBILE),
    ("coupures", "coupures reseau toutes les 10 minutes a ariana", Category.RESEAU_MOBILE),
    ("3g", "bloque en 3g alors que je paye un forfait 4g illimite", Category.RESEAU_MOBILE),
    ("reseau nul", "el reseau khayeb barcha fel medina", Category.RESEAU_MOBILE),

    # ------------------------------------------------------- INTERNET_FIXE
    ("fibre", "fibre coupee depuis 9 jours, je teletravaille", Category.INTERNET_FIXE),
    ("adsl lent", "je paye 20 mega je recois 2 mega en filaire", Category.INTERNET_FIXE),
    ("box", "la box clignote rouge en boucle depuis mardi", Category.INTERNET_FIXE),
    ("انترنت", "الانترنت القار مقطوع من جمعة", Category.INTERNET_FIXE),
    ("deconnexion", "connexion qui saute toutes les 10 min impossible de travailler", Category.INTERNET_FIXE),
    ("internet", "el internet fel dar ma ye5demch men 3 iyem", Category.INTERNET_FIXE),
    ("debit", "debit divise par 10 depuis le passage a la fibre", Category.INTERNET_FIXE),
    ("ligne fixe", "plus de tonalite et plus d internet sur la ligne fixe", Category.INTERNET_FIXE),
    ("wifi", "aucune connexion depuis l orage de samedi", Category.INTERNET_FIXE),
    ("internet", "no internet at home since friday, three calls no fix", Category.INTERNET_FIXE),
    ("adsl", "ligne adsl instable la nuit uniquement", Category.INTERNET_FIXE),
    ("fibre", "installee il y a 2 semaines, deja 4 pannes", Category.INTERNET_FIXE),
    ("connexion", "debit correct le matin, inexistant le soir, tous les jours", Category.INTERNET_FIXE),
    ("صبيب", "الصبيب ضعيف برغم اني خالص عرض 20 ميغا", Category.INTERNET_FIXE),
    ("panne internet", "voisins tous coupes aussi, probleme sur le quartier", Category.INTERNET_FIXE),

    # ----------------------------------------------- INTERVENTION_TECHNIQUE
    ("rdv", "technicien jamais venu, j ai pose un conge pour rien", Category.INTERVENTION_TECHNIQUE),
    ("intervention", "dossier ouvert depuis 3 semaines, zero nouvelle", Category.INTERVENTION_TECHNIQUE),
    ("تقني", "التقني ما جاش و ما عيطش", Category.INTERVENTION_TECHNIQUE),
    ("cable", "cable arrache par les travaux devant chez moi", Category.INTERVENTION_TECHNIQUE),
    ("technicien", "el technicien ma jech w 3malt conge", Category.INTERVENTION_TECHNIQUE),
    ("delai", "72h annoncees, on est a 15 jours", Category.INTERVENTION_TECHNIQUE),
    ("rendez vous", "3eme rdv annule par vos services sans prevenir", Category.INTERVENTION_TECHNIQUE),
    ("depannage", "on attend une piece depuis un mois sans nouvelle", Category.INTERVENTION_TECHNIQUE),
    ("visit", "the technician cancelled three times in a row", Category.INTERVENTION_TECHNIQUE),
    ("intervention", "constat fait par le technicien, aucune suite donnee", Category.INTERVENTION_TECHNIQUE),
    ("poteau", "poteau tombe dans la rue, ligne au sol, dangereux", Category.INTERVENTION_TECHNIQUE),
    ("تدخل", "من شهر و انا نستنى في التدخل", Category.INTERVENTION_TECHNIQUE),
    ("raccordement", "raccordement promis sous 10 jours, toujours rien apres 2 mois", Category.INTERVENTION_TECHNIQUE),
    ("SAV", "personne ne se deplace malgre 5 appels au service technique", Category.INTERVENTION_TECHNIQUE),
    ("installation", "installation reportee 4 fois, je perds patience", Category.INTERVENTION_TECHNIQUE),

    # ----------------------------------------------------- OFFRES_ABONNEMENT
    ("promo", "promo 2 mois offerts jamais appliquee", Category.OFFRES_ABONNEMENT),
    ("forfait", "j ai demande le changement de forfait il y a 6 semaines", Category.OFFRES_ABONNEMENT),
    ("عرض", "العرض ما تفعلش رغم اني اشتركت", Category.OFFRES_ABONNEMENT),
    ("offre", "on m a vendu 12 mois d engagement le contrat dit 24", Category.OFFRES_ABONNEMENT),
    ("abonnement", "baddlouli el forfait bla ma nab3ath talab", Category.OFFRES_ABONNEMENT),
    ("promotion", "la remise affichee sur le site ne figure pas sur ma ligne", Category.OFFRES_ABONNEMENT),
    ("plan", "i subscribed to the family offer, it was never activated", Category.OFFRES_ABONNEMENT),
    ("option", "option internet souscrite non active apres 4 jours", Category.OFFRES_ABONNEMENT),
    ("forfait", "migration vers offre superieure facturee mais pas effective", Category.OFFRES_ABONNEMENT),
    ("engagement", "on refuse de me laisser partir a cause d un engagement fantome", Category.OFFRES_ABONNEMENT),
    ("اشتراك", "بدلولي العرض بلا اذني و الثمن زاد", Category.OFFRES_ABONNEMENT),
    ("offre familia", "familia desactivee sans preavis ni explication", Category.OFFRES_ABONNEMENT),
    ("tarif", "tarif change en cours de contrat, jamais informe", Category.OFFRES_ABONNEMENT),
    ("promo", "el promo eli fel affiche ma tطbقatech 3lia", Category.OFFRES_ABONNEMENT),
    ("bonus", "bonus data promis a la souscription jamais credite", Category.OFFRES_ABONNEMENT),

    # ------------------------------------------------ RESILIATION_PORTABILITE
    ("resiliation", "resilie il y a 2 mois, toujours facture", Category.RESILIATION_PORTABILITE),
    ("portabilite", "portabilite bloquee, je perds mon numero pro", Category.RESILIATION_PORTABILITE),
    ("فسخ", "طلبت الفسخ و مازلت نخلص كل شهر", Category.RESILIATION_PORTABILITE),
    ("resilier", "je veux resilier, personne ne traite ma demande", Category.RESILIATION_PORTABILITE),
    ("changer operateur", "nhab nbadel operateur w ma5allounich", Category.RESILIATION_PORTABILITE),
    ("cloture", "compte toujours actif malgre lettre recommandee", Category.RESILIATION_PORTABILITE),
    ("cancel", "i cancelled last month and i am still being billed", Category.RESILIATION_PORTABILITE),
    ("portabilite", "3 echecs de portabilite sans aucune explication", Category.RESILIATION_PORTABILITE),
    ("resiliation", "accuse de reception en main, aucune suite depuis 5 semaines", Category.RESILIATION_PORTABILITE),
    ("transfert numero", "mon numero n a jamais ete transfere chez vous", Category.RESILIATION_PORTABILITE),
    ("نقل الرقم", "نقل الرقم مبلوك من ثلاث اسابيع", Category.RESILIATION_PORTABILITE),
    ("depart", "je pars a la concurrence, liberez ma ligne", Category.RESILIATION_PORTABILITE),
    ("resiliation", "frais de resiliation reclames alors que j etais hors engagement", Category.RESILIATION_PORTABILITE),
    ("fasakh", "3malt talab fasakh w mazelt nkhalas", Category.RESILIATION_PORTABILITE),
    ("abonnement", "arret du prelevement demande, toujours preleve", Category.RESILIATION_PORTABILITE),

    # ---------------------------------------------- SERVICE_CLIENT_AGENCE
    ("agence", "2h d attente pour une sim, 2 guichets sur 6", Category.SERVICE_CLIENT_AGENCE),
    ("service client", "ligne qui raccroche apres le message d accueil", Category.SERVICE_CLIENT_AGENCE),
    ("وكالة", "قعدت ساعتين في الوكالة و ما تحلش شي", Category.SERVICE_CLIENT_AGENCE),
    ("agent", "l agent m a parle tres mal et a refuse de donner son nom", Category.SERVICE_CLIENT_AGENCE),
    ("call center", "n3ayet men sbe7 w 7atta wa7ed ma yjaweb", Category.SERVICE_CLIENT_AGENCE),
    ("rappel", "3 promesses de rappel sous 24h, aucun rappel", Category.SERVICE_CLIENT_AGENCE),
    ("support", "nobody ever answers the customer service line", Category.SERVICE_CLIENT_AGENCE),
    ("accueil", "agence fermee en pleine journee sans affichage", Category.SERVICE_CLIENT_AGENCE),
    ("conseiller", "on me renvoie d un service a l autre depuis 3 semaines", Category.SERVICE_CLIENT_AGENCE),
    ("خدمة الحرفاء", "عيطت برشة مرات و حتى واحد ما جاوبني", Category.SERVICE_CLIENT_AGENCE),
    ("file", "systeme de tickets en panne, tout le monde attend debout", Category.SERVICE_CLIENT_AGENCE),
    ("agent", "on m a raccroche au nez deux fois de suite", Category.SERVICE_CLIENT_AGENCE),
    ("reclamation", "ma reclamation deposee en agence n a jamais ete enregistree", Category.SERVICE_CLIENT_AGENCE),
    ("guichet", "el agence tetsakker 3la 15h w famech information", Category.SERVICE_CLIENT_AGENCE),
    ("attente", "45 minutes en attente telephonique puis coupure", Category.SERVICE_CLIENT_AGENCE),

    # -------------------------------------------------------------- EQUIPEMENT
    ("routeur", "routeur neuf ne s allume pas du tout", Category.EQUIPEMENT),
    ("decodeur", "decodeur redemarre toutes les 5 minutes", Category.EQUIPEMENT),
    ("sim", "puce non reconnue par 2 telephones differents", Category.EQUIPEMENT),
    ("تجهيز", "التجهيز الجديد ما يخدمش خاطر", Category.EQUIPEMENT),
    ("box", "el box tsakhen barcha w tetfa wa7adha", Category.EQUIPEMENT),
    ("materiel", "on refuse l echange malgre la garantie de 12 mois", Category.EQUIPEMENT),
    ("router", "the router died after three weeks and nobody replaces it", Category.EQUIPEMENT),
    ("cable", "cable ethernet manquant dans le carton du modem", Category.EQUIPEMENT),
    ("sim", "carte sim illisible recue par la poste", Category.EQUIPEMENT),
    ("decodeur", "image qui gele en permanence sur la tv", Category.EQUIPEMENT),
    ("شريحة", "الشريحة ما تتقراش في التلفون", Category.EQUIPEMENT),
    ("modem", "modem fourni obsolete, incompatible avec la fibre installee", Category.EQUIPEMENT),
    ("telephone", "terminal achete en boutique defectueux des le premier jour", Category.EQUIPEMENT),
    ("materiel", "le materiel restitue m est toujours facture", Category.EQUIPEMENT),
    ("box", "voyants eteints, alimentation testee sur 3 prises", Category.EQUIPEMENT),

    # --------------------------------------------------- ROAMING_INTERNATIONAL
    ("roaming", "340 dt de roaming apres 5 jours en italie", Category.ROAMING_INTERNATIONAL),
    ("international", "appels vers la france factures 3x le tarif annonce", Category.ROAMING_INTERNATIONAL),
    ("تجوال", "معاليم التجوال غالية برغم العرض الدولي", Category.ROAMING_INTERNATIONAL),
    ("pass", "pass international paye jamais active a l etranger", Category.ROAMING_INTERNATIONAL),
    ("roaming", "rja3t men turkiya w jatni facture 500 dinar", Category.ROAMING_INTERNATIONAL),
    ("data etranger", "data en itinerance facturee alors que desactivee", Category.ROAMING_INTERNATIONAL),
    ("abroad", "huge roaming bill even though i bought the travel pass", Category.ROAMING_INTERNATIONAL),
    ("appels", "impossible d appeler la tunisie depuis l allemagne", Category.ROAMING_INTERNATIONAL),
    ("itinerance", "aucun reseau partenaire disponible pendant tout le sejour", Category.ROAMING_INTERNATIONAL),
    ("roaming", "facture roaming recue 2 mois apres le retour", Category.ROAMING_INTERNATIONAL),
    ("دولي", "المكالمات الدولية غالية اكثر من المعلن", Category.ROAMING_INTERNATIONAL),
    ("sejour", "sms surtaxes a l etranger sans aucun avertissement", Category.ROAMING_INTERNATIONAL),
    ("pass international", "pass achete la veille du depart, jamais fonctionne", Category.ROAMING_INTERNATIONAL),
    ("roaming", "el roaming ghali barcha, 3lech ma 9alouliech?", Category.ROAMING_INTERNATIONAL),
    ("etranger", "coupure totale de service des le passage de la frontiere", Category.ROAMING_INTERNATIONAL),

    # ---------------------------------------------------- APPLICATION_MOBILE
    ("appli", "impossible de me connecter depuis la mise a jour", Category.APPLICATION_MOBILE),
    ("application", "ecran blanc au demarrage, rien ne charge", Category.APPLICATION_MOBILE),
    ("تطبيق", "التطبيق يسكر وحدو كل مرة", Category.APPLICATION_MOBILE),
    ("app", "solde affiche faux, ussd donne le bon montant", Category.APPLICATION_MOBILE),
    ("appli", "l app tetsakker wa9t nhel", Category.APPLICATION_MOBILE),
    ("bug", "bouton payer ne repond pas dans l application", Category.APPLICATION_MOBILE),
    ("app", "the app crashes every time i open the bills section", Category.APPLICATION_MOBILE),
    ("connexion", "identifiants refuses alors que le mot de passe est bon", Category.APPLICATION_MOBILE),
    ("historique", "historique de consommation vide depuis la mise a jour", Category.APPLICATION_MOBILE),
    ("application", "notification de facture recue mais rien dans l appli", Category.APPLICATION_MOBILE),
    ("تطبيق", "التطبيق ما يفتحش من بعد التحديث", Category.APPLICATION_MOBILE),
    ("appli", "desinstalle reinstalle 4 fois, meme probleme", Category.APPLICATION_MOBILE),
    ("espace client", "site web et appli affichent des soldes differents", Category.APPLICATION_MOBILE),
    ("app", "l application demande une mise a jour qui n existe pas sur le store", Category.APPLICATION_MOBILE),
    ("login", "code otp jamais recu pour se connecter a l application", Category.APPLICATION_MOBILE),

    # ------------------------------------------- deliberately unclassifiable
    # These should come back low-confidence and land in human triage. If the
    # model confidently labels them, the confidence threshold is not working.
    ("probleme", "bonjour j ai un probleme", None),
    ("aide", "aidez moi svp", None),
    ("?", "c est quoi ca", None),
    ("urgent", "URGENT", None),
    ("reclamation", "je suis tres mecontent de vos services", None),
    ("مشكل", "عندي مشكل", None),
    ("mochkel", "3andi mochkel", None),
    ("service", "rien ne marche chez vous", None),
    ("bonjour", "bonjour", None),
    ("info", "je voudrais des renseignements", None),
    ("question", "est ce que vous pouvez m aider", None),
    ("svp", "merci de me rappeler", None),
    ("reclamation", "toujours les memes problemes avec vous", None),
    ("nul", "nul", None),
    ("mauvais", "service catastrophique", None),
    ("aide", "je ne sais pas quoi faire", None),
    ("appel", "rappelez moi au plus vite", None),
    ("خدمة", "الخدمة خايبة", None),
    ("yezzi", "yezzi barcha", None),
    ("help", "please help me", None),
    ("probleme", "ca ne fonctionne pas", None),
    ("reclamation", "deuxieme reclamation ce mois ci", None),
    ("suivi", "ou en est mon dossier", None),
    ("dossier", "aucune nouvelle de ma demande", None),
    ("?", "vous faites quoi la", None),
    ("client", "je suis client depuis 15 ans et voila comment on me traite", None),
    ("scandale", "c est un scandale", None),
    ("avocat", "je vais voir mon avocat", None),
    ("stop", "arretez tout", None),
    ("merci", "merci de traiter rapidement", None),
    ("رد", "ننتظر الرد منكم", None),
    ("mochkla", "3andi mochkla kbira barcha", None),
    ("reponse", "j attends une reponse depuis longtemps", None),
    ("test", "test", None),
    ("...", "........", None),
    ("plainte", "je porte plainte", None),
    ("assez", "trop c est trop", None),
    ("service", "inadmissible", None),
    ("suivi dossier", "quel est le statut", None),
    ("rappel", "personne ne me rappelle jamais", None),
]
